listen_addresses = '*'
hba_file = '/var/lib/postgresql/18/docker/pg_hba.conf'
ident_file = '/var/lib/postgresql/18/docker/pg_ident.conf'

max_connections = 100

shared_buffers = 1GB
effective_cache_size = 3GB
work_mem = 16MB
maintenance_work_mem = 256MB
huge_pages = try

wal_buffers = 64MB
min_wal_size = 1GB
max_wal_size = 8GB
checkpoint_completion_target = 0.9

random_page_cost = 1.1
effective_io_concurrency = 200

max_worker_processes = 4
max_parallel_workers = 4
max_parallel_workers_per_gather = 2
max_parallel_maintenance_workers = 2

track_io_timing = on
