global:
  scrape_interval: 2s
  scrape_timeout: 2s

scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets: [fastapi-1-inst:8001]
    relabel_configs: &host-instance
      - source_labels: [__address__]
        regex: '(.+):\d+'
        target_label: instance

  - job_name: celery
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: [client-1-inst:9808]

  - job_name: postgres
    static_configs:
      - targets: [postgres-inst:9187]

  - job_name: redis
    static_configs:
      - targets: [redis-auth-inst:9121]

  - job_name: node
    static_configs:
      - targets: [fastapi-1-inst:9100, celery-1-inst:9100, postgres-inst:9100, redis-auth-inst:9100]
      - targets: [client-1-inst:9100]
        labels:
          role: client
    relabel_configs: *host-instance

  - job_name: cadvisor
    static_configs:
      - targets: [fastapi-1-inst:8080, celery-1-inst:8080, postgres-inst:8080, redis-auth-inst:8080]
      - targets: [client-1-inst:8080]
        labels:
          role: client
    relabel_configs: *host-instance
    metric_relabel_configs:
      - source_labels: [id]
        regex: '.*/libpod-conmon-.*|.+/'
        action: drop
