QUANTIZE_TASK = "worker.tasks.quantize_submission"
VALIDATE_TASK = "worker.tasks.validate_submission"
FED_AGG_TASK = "worker.tasks.federated_aggregation"
SECURE_AGG_TASK = "worker.tasks.secure_aggregation"
CLEANUP_TASK = "worker.tasks.cleanup_results"
